# Generated by Django 5.2 on 2025-05-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_reactions'),
        ('reactions', '0002_initial_reaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereaction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlereaction_set', to='main.article'),
        ),
    ]
