# Generated by Django 5.2 on 2025-05-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_reactions'),
        ('reactions', '0003_alter_articlereaction_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlereaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='articlereaction',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='reaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reactions.reactiontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlereaction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reactions', to='main.article'),
        ),
    ]
