# Generated by Django 5.2 on 2025-05-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_alter_articlereaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlereaction',
            options={'verbose_name': 'Article Reaction', 'verbose_name_plural': 'Article Reactions'},
        ),
        migrations.RemoveField(
            model_name='articlereaction',
            name='reaction',
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='reaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reactions.reactiontype'),
            preserve_default=False,
        ),
    ]
