# Generated by Django 5.2 on 2025-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
