# Generated by Django 5.2 on 2025-05-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_article_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
            preserve_default=False,
        ),
    ]
