# Generated by Django 5.2 on 2025-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_article_cat'),
        ('reactions', '0002_initial_reaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reactions',
            field=models.ManyToManyField(related_name='articles', through='reactions.ArticleReaction', to='reactions.reactiontype'),
        ),
    ]
