# Generated by Django 5.2 on 2025-05-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reactions',
        ),
    ]
