# Generated by Django 5.2 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_article_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
